"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by create next app",
// };

const navLinks = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forgot Password", href: "/forgotpassword" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const [input, setInput] = useState("");

  return (
    <>
      <div className="p-4">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          className="outline rounded-sm"
        />
      </div>
      {children}
      {navLinks.map((link) => {
        const isActive = pathname.startsWith(link.href);
        return (
          <Link
            key={link.name}
            href={link.href}
            className={
              isActive
                ? "text-yellow-400 font-serif font-bold"
                : "text-red-400 font-sans"
            }>
            {link.name}
          </Link>
        );
      })}
    </>
  );
}
