import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Riviera", "sans-serif"],
      },
      aspectRatio: {
        square: "1, 1",
      },
      fontSize: {
        root: "18px",
        "h1-sm": "2.11rem",
        "h1-lg": "2.22rem",
        "h2-sm": "1.66rem",
        "h2-lg": "2.22rem",
        "h3-sm": "1rem",
        "h3-sm-desc": "1rem",
        "h3-lg": "1.44rem",
        "h3-lg-desc": "1.55rem",
        "h4-sm": "1.22rem",
        "h4-lg": "1.55rem",
        "h4-sm-sticky": "1.66rem",
        "h4-lg-sticky": "2.22rem",
        "p-sm": "1rem",
        "p-lg": ".88rem",
        "p-modal": "1.33rem",
        "span-sm": "1rem",
        "span-lg": "1.125rem",
        "button-sm": "1rem",
        "button-lg": "1.11rem",
        "span-desc": "0.88rem",
        "span-press-excerpt": "0.88rem",
      },
      lineHeight: {
        "h1-sm": "2.6rem",
        "h1-lg": "2.66rem",
        "h2-sm": "2rem",
        "h2-lg": "2.22rem",
        "h3-sm": "1.8rem",
        "h3-sm-desc": "1.77rem",
        "h3-lg": "2rem",
        "h3-lg-desc": "2.22rem",
        "h4-sm": "2.22rem",
        "h4-lg": "2.22rem",
        "h4-sm-sticky": "2.33rem",
        "h4-lg-sticky": "2.66rem",
        "p-sm": "1.77rem",
        "p-lg": "1.55rem",
        "p-modal": "1.5rem",
        "span-sm": "1.5rem",
        "span-lg": "1.5rem",
        "button-sm": "1.22rem",
        "button-lg": "1.33rem",
        "span-desc": "1rem",
        "span-press-excerpt": "1.33rem",
      },
      fontWeight: {
        "h1-sm": "700",
        "h1-lg": "700",
        "h2-sm": "700",
        "h2-lg": "700",
        "h3-sm": "400",
        "h3-sm-desc": "400",
        "h3-lg": "500",
        "h3-lg-desc": "500",
        "h4-sm": "700",
        "h4-lg": "500",
        "h4-sm-sticky": "700",
        "h4-lg-sticky": "700",
        "p-sm": "400",
        "p-lg": "400",
        "span-sm": "700",
        "span-lg": "700",
        "button-sm": "700",
        "button-lg": "700",
        "span-desc": "400",
        light: "100",
        normal: "400",
        medium: "500",
        bold: "700",
      },
      colors: {
        body: "#343D55",
        peach: "#FC855F",
        gray: {
          slate: "#3D3538",
          light: "#E0E0E0",
        },
        white: {
          DEFAULT: "#FFFFFF",
          smoke: "#F7F7F7",
        },
        blue: {
          smoke: "#E5F1FE",
          slate: "#343D55",
          sky: "#A8C6D8",
        },
        yellow: {
          DEFAULT: "#E1C672",
          tint: "#F3E8C8",
        },
        mandyspink: {
          DEFAULT: "#f5cdbd",
        },
        lightGray: "#f7f7f7",
        darkGray: "#727272",
        cream: "#FFFBF3",
        lightOrange: "#FFE9DD",
        lightBlue: "#F1F7FB",
        teal: "#497996",
        navyBlue: "#343D55",
      },
      borderRadius: {
        hero: "3.5rem",
      },
      flexGrow: {
        half: "0.5",
      },
      flexBasis: {
        half: "50%",
      },
      minHeight: {
        contentImage: "500px",
      },
      typography: {
        DEFAULT: {
          css: {
            color: "#343D55",
            h1: {
              margin: "0",
              fontSize: "2.11rem",
              lineHeight: "2.5rem",
              fontWeight: "700",
              color: "inherit",
            },
            h2: {
              margin: "0 0 1.11rem 0",
              width: "100%",
              fontSize: "1.66rem",
              lineHeight: "2rem",
              fontWeight: "700",
              color: "inherit",
            },
            h3: {
              margin: "0",
              fontSize: "1rem",
              lineHeight: "1.8rem",
              fontWeight: "700",
              color: "inherit",
            },
            h4: {
              margin: "0 0 1.11rem 0",
              fontSize: "1.22rem",
              lineHeight: "2.22rem",
              fontWeight: "700",
              color: "inherit",
            },
            h5: {
              margin: "0 0 1.11rem 0",
              fontSize: "1rem",
              lineHeight: "1.77rem",
              fontWeight: "400",
              color: "inherit",
            },
            p: {
              margin: "0 0 1.11rem 0",
              fontSize: "1rem",
              lineHeight: "1.77rem",
              fontWeight: "400",
              color: "inherit",
            },
            span: {
              margin: "0 0 1.11rem 0",
              fontSize: "1rem",
              lineHeight: "1.33rem",
              fontWeight: "400",
              color: "inherit",
            },
            strong: { color: "inherit", fontWeight: "700" },
            em: { color: "inherit" },
            a: {
              color: "inherit",
              overflowWrap: "break-word",
            },
          },
        },
        lg: {
          css: {
            h1: {
              margin: "0 0 1.22rem 0",
              fontSize: "2.22rem",
              lineHeight: "2.66rem",
              fontWeight: "700",
              color: "inherit",
            },
            h2: {
              margin: "0 0 1.2rem 0",
              fontSize: "2rem",
              lineHeight: "2.44rem",
              fontWeight: "700",
              color: "inherit",
            },
            h3: {
              fontSize: "1.11rem",
              lineHeight: "1.5rem",
              fontWeight: "700",
              color: "inherit",
            },
            h4: {
              fontSize: "1.55rem",
              lineHeight: "2.22rem",
              fontWeight: "500",
              color: "inherit",
            },
            h5: {
              margin: "0 0 1.11rem 0",
              fontSize: "1.211rem",
              lineHeight: "2rem",
              fontWeight: "400",
              color: "inherit",
            },
            p: {
              margin: "0 0 1.11rem 0",
              fontSize: "0.88rem",
              lineHeight: "1.55rem",
              fontWeight: "400",
              color: "inherit",
            },
            span: {
              fontSize: "0.77rem",
              lineHeight: "1.11rem",
              fontWeight: "400",
              color: "inherit",
            },
            strong: { color: "inherit", fontWeight: "700" },
            em: { color: "inherit" },
            a: {
              color: "inherit",
              overflowWrap: "break-word",
            },
          },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/aspect-ratio"),
  ],
};
export default config;
